parameters:
    campaignchain.operation.campaignchain.xing.message:
        bundle_name: "campaignchain/operation-xing"
        module_identifier: "campaignchain-xing-message"
        form_type: "CampaignChain\\Operation\\XingBundle\\Form\\Type\\XingMessageOperationType"

services:
    campaignchain.job.operation.campaignchain.xing.message:
        class: CampaignChain\Operation\XingBundle\Job\XingMessage
        arguments: [ @doctrine.orm.entity_manager, @service_container ]
    campaignchain.job.report.campaignchain.xing.message:
        class: CampaignChain\Operation\XingBundle\Job\XingMessageReport
        arguments: [ @doctrine.orm.entity_manager, @service_container ]
    campaignchain.operation.campaignchain.xing.message:
        class: CampaignChain\Operation\XingBundle\EntityService\XingMessage
        arguments: [ @doctrine.orm.entity_manager ]